name: RedisBungee
main: com.imaginarycode.minecraft.redisbungee.RedisBungee
version: ${project.parent.version}
author: "astei, ProxioDev"
# This is used so that we can automatically override default BungeeCord behavior.
softDepends: ["cmd_find", "cmd_list"]